### ISSUE TITLE
bug: No SwEvent.Ready event if gateway status is already REGED

### ISSUE THREAD

**Issue by JorgeFraga** [team-telnyx/webrtc#217]
Due to the change on 361f9220cbcb0acc6ddbfc331add17b20adfb052, from version 2.5.7 it is possible for the `SwEvent.Ready` event to never be fired if the gateway is already in the REGED state. It can be reproduced sometimes by just refreshing the page with the telnyx client.

Attached is the network log in one such request. You can see that a `method: telnyx_rtc.gatewayState` with state REGED never arrives, so [this line](https://github.com/team-telnyx/webrtc/blob/361f9220cbcb0acc6ddbfc331add17b20adfb052/packages/js/src/Modules/Verto/webrtc/VertoHandler.ts#L155) will not run.

![image](https://user-images.githubusercontent.com/4301197/140910528-53614417-d48f-4441-bf2e-e2b5875bd0a5.png)

**Comment by DeividVeloso** [comment]
@JorgeFraga the problem is on the backend side if you take a look the latest messages are FAILED and FAILED_WAIT that comes from the backend, when this happens the connection between SDK and Server is closed.
I recommend using the WebRTC SDK version 2.6.0 and read the change log, it will help to mitigate this error until the backend release a solution.

https://github.com/team-telnyx/webrtc/releases/tag/webrtc%2Fv2.6.0

**Comment by gmcabrita** [comment]
@DeividVeloso Please notice that the `FAILED` and `FAIL_WAIT` only arrive nearly 3 minutes after the initial `telnyx_rtc.gatewayState` which already receives the `state: "REGED"` response.

We only found this issue after having updated to 2.5.7 (which caused us to revert to a previous version). When 2.6.0 came out we found it had the same issue still as it's not related with retrying specifically.

> I recommend using the WebRTC SDK version 2.6.0 and read the change log, it will help to mitigate this error until the backend release a solution.

In 2.6.0 with the auto reconnect enabled the same issue still exists, except that when that `FAILED` for some reason comes in after ~3 minutes it then tries to auto reconnect.

Our issue is orthogonal to auto reconnect, since from the messages it seems we clearly managed to register correctly. The webrtc client just seems to be ignoring that the registration with the gateway is already done and does not issue the SwEvent.Ready.

In 2.5.6 this continues to not be a problem, as when this case specifically happens we received the ready event and can start issuing phone calls with no problem.

**Comment by DeividVeloso** [comment]
Hello @gmcabrita can you provide a demo project that I can look into it?

I've tested here using version 2.6.0 and I'm receiving the `telnyx.ready` in my client UI app when I receive from the server the message `REGED`

```
    clientRef.current.on('telnyx.ready', () => {
        logActions.push({ id: 'registered', description: 'registered' });
        setRegistered(true);
      });
```

![image](https://user-images.githubusercontent.com/16343871/141305203-5c5bd86f-f1cd-4076-85ed-9ee4b84c0539.png)

And looking into @JorgeFraga  comment I can see the `REGED` message in the fifth message:

```
Attached is the network log in one such request. You can see that a method: telnyx_rtc.gatewayState with state REGED never arrives, so this line will not run.
```

**Comment by gmcabrita** [comment]
Thanks for the link to the https://webrtc.telnyx.com/ I have managed to reproduce the issue there. It seems the issue only happens when using token-based authentication.

I recorded a small video where you can see after some reconnects I'm unable to start a call (client seems to not be ready): https://user-images.githubusercontent.com/957820/141456144-c2cf7584-b298-4e21-a43a-86ba0f465269.mp4

**Comment by DeividVeloso** [comment]
Hey @gmcabrita, thank you for the video.

I will investigate and I will let you know as soon as possible.

**Comment by DeividVeloso** [comment]
@gmcabrita I'm trying to reproduce here, but it is not happening at the moment
![image](https://user-images.githubusercontent.com/16343871/141504261-64cec662-01f8-4f6c-a8d8-ca9293a5c9ec.png)

Could you open the `console` tab from the browser and try to test again and when the latest `unregister` comes, could check if it has some error message in the console browser, please?

**Comment by gmcabrita** [comment]
@DeividVeloso There doesn't seem to be an error. The last log is from the `telnyx_rtc.clientReady` received from the backend, before issuing the `telnyx_rtc.gatewayState`.

https://user-images.githubusercontent.com/957820/141513057-a02a4362-19d4-4662-be92-2e739fecf5bc.mp4

**Comment by DeividVeloso** [comment]
@gmcabrita we just released a new internal SDK version with the fix for the issue that you reported, can you test here https://webrtc.telnyx.com and see if solved it?

We are doing more tests and if solved for you probably we will release a new public SDK version until the end of the week.

**Comment by gmcabrita** [comment]
@DeividVeloso Seems the issue is still happening on webrtc.telnyx.com (version 2.6.1)

https://user-images.githubusercontent.com/957820/141969996-4cc8e170-0d56-43ae-abc9-4dd1a79ad5cc.mp4

**Comment by DeividVeloso** [comment]
Hey @gmcabrita thank you so much for testing it.

Could you do me a favor of copying the entire last message `REGED` on websocket and past here, please?

For example:
![image](https://user-images.githubusercontent.com/16343871/141991959-13a014a8-a396-4029-bcac-016a082cb177.png)

but in your case the last message when the `unregister` happens

**Comment by gmcabrita** [comment]
@DeividVeloso This is the message:

```
{"jsonrpc":"2.0","id":"b238e933-2f8f-48df-beb2-4349f9d898a7","result":{"params":{"state":"REGED"},"sessid":"57ac03e3-a6cd-4a33-a0f1-25bb43328c03"}}
```

**Comment by DeividVeloso** [comment]
@gmcabrita could you please test again here https://webrtc.telnyx.com? 
I've just released a new internal version.

**Comment by gmcabrita** [comment]
@DeividVeloso It seems correctly publishes the client ready event now!

Only weird thing I noticed while testing it was that sometimes there were duplicate calls to telnyx_rtc.gatewayState, but it seems to work fine regardless:
![image](https://user-images.githubusercontent.com/957820/142419825-e8f4e347-fc7f-4e38-a7d4-7f44e0530107.png)

**Comment by DeividVeloso** [comment]
This Telnyx `telnyx_rtc.gatewayState` is used to ask the server if the user is registered and ready to make calls, if it is not registered `UNREGED` we send again the  `telnyx_rtc.gatewayState` until `FAIL` or until be registered `REGED`

**Comment by DeividVeloso** [comment]
@gmcabrita we have just released a new public version 2.6.1 with the fix. Can you try it, please?

**Comment by gmcabrita** [comment]
Seems to be working fine for us now @DeividVeloso 👍

**Comment by DeividVeloso** [comment]
Fixed in the SDK version 2.6.1
